version: '3.8'

services:
  db:
    container_name: test_url

    ports:
      - "5438:5432"

    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=qwerty
    image: postgres:15.2-alpine
